version: '3'

services:                       
  docs:
    image: miko089.ru/docs:latest
    restart: always
    ports:
      - 8888:80
    labels:
      - "traefik.http.routers.docs.rule=Host(`docs.miko089.ru`)"

  reverse-proxy:
    image: traefik:v2.10
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
