version: '3'

services:                       
  docs:
    image: miko089.ru/docs:latest
    restart: always
    ports:
      - 8888:80
    labels:
      - "traefik.http.routers.docs.rule=Host(`docs.miko089.ru`)"

  postgresql:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: new-tube
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    
    volumes:
      - /home/new-tube/new-tube/db_data:/var/lib/postgresql/data

  internal-api:
    image: miko089.ru/internal-api:latest
    restart: always
    ports:
      - 5050:5050
    labels:
      - "traefik.http.routers.internal.rule=Host(`localhost:5050`)"
    networks:
      - main

  test-client-internal-api:
    image: miko089.ru/test-internal-api:latest
    restart: always
    ports:
      - 5000:8080
    labels:
      - "traefik.http.routers.test.rule=Host(`test.miko089.ru:5000`)"
    networks:
      - main

  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "12:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - main

networks:
  main:
