version: '3'

services:                       
  docs:
    image: new-tube.ru/docs:latest
    restart: always
    ports:
      - 8001:80
    labels:
      - "traefik.http.routers.docs.rule=Host(`docs.new-tube.ru`)"

  postgresql:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: new-tube
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    labels:
      - "traefik.http.routers.database.rule=Host(`database:5432`)"
    volumes:
      - /home/new-tube/new-tube/db_data:/var/lib/postgresql/data

  internal-api:
    image: new-tube.ru/internal-api:latest
    restart: always
    ports:
      - 5050:5050
    labels:
      - "traefik.http.routers.internal.rule=Host(`internal-api:5050`)"
    volumes:
      - /home/new-tube/new-tube/server/.env:/app/.env

  regular-user-web-interface:
    image: new-tube.ru/regular-user-web-interface:latest
    restart: always
    ports:
      - 8002:8080
    labels:
      - "traefik.http.routers.regular-user-web.rule=Host(`new-tube.ru`)"

  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "12:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
  restart: always
  image: registry:2
  ports:
    - 8003:443

  labels:
    - "traefik.http.routers.registry.rule=Host(`registry.new-tube.ru`)"
    - "traefik.http.routers.myrouter.tls=true"

  environment:
    REGISTRY_HTTP_ADDR: 0.0.0.0:443
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.new-tube.fullchain.pem
    REGISTRY_HTTP_TLS_KEY: /certs/registry.new-tube.key.pem
      
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
    REGISTRY_AUTH_HTPASSWD_PATH: /config/htpasswd

  volumes:
    - /home/new-tube/new-tube/server/certs:/certs
    - /home/new-tube/new-tube/server/registry:/var/lib/registry
    - /home/new-tube/new-tube/server/config:/config
