services:
  nginx:
    image: nginx:stable
    restart: always

    ports:
    - 80:80
    environment:
    - NGINX_HOST=miko089.ru
    - NGINX_PORT=80

  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
  docs:
    image: miko089.ru/docs
    restart: always
    ports:
      - 8001:80
