version: '3'

services:                       
  docs:
    image: new-tube.ru/docs:latest
    restart: always
    ports:
      - 8001:80
    labels:
      - "traefik.http.routers.docs.rule=Host(`docs.new-tube.ru`)"

  postgresql:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: new-tube
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    labels:
      - "traefik.http.routers.database.rule=Host(`database:5432`)"
    volumes:
      - /home/new-tube/new-tube/db_data:/var/lib/postgresql/data

  internal-api:
    image: new-tube.ru/internal-api:latest
    restart: always
    ports:
      - 5050:5050
    labels:
      - "traefik.http.routers.internal.rule=Host(`internal-api:5050`)"
    volumes:
      - /home/new-tube/new-tube/server/.env:/app/.env

  regular-user-web-interface:
    image: new-tube.ru/regular-user-web-interface:latest
    restart: always
    ports:
      - 8002:8080
    labels:
      - "traefik.http.routers.regular-user-web.rule=Host(`new-tube.ru`)"

  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "12:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
